const data = {
  products: [
    {
      id: 1,
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 45,
      brand: "Nike",
      color: "red",
      size: "M",
      countInStock: 10,
      rating: 4.6,
      numReviews: 15,
      description: "A spring shirt",
    },
    {
      id: 2,
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 75,
      brand: "Adidas",
      color: "pink",
      size: "S",
      countInStock: 30,
      rating: 5,
      numReviews: 5,
      description: "A sport outfit for all gender",
    },
    {
      id: 3,
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 45,
      brand: "Zara",
      color: "stripped",
      size: "XL",
      countInStock: 45,
      rating: 4.8,
      numReviews: 20,
      description: "A spring shirt",
    },
    {
      id: 4,
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 45,
      brand: "Savero",
      color: "Blue ",
      size: "M",
      countInStock: 12,
      rating: 4.8,
      numReviews: 35,
      description: "A smart looking pants",
    },
    {
      id: 5,
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pant",
      image: "/images/pants2.jpg",
      price: 45,
      brand: "Nike",
      color: "red",
      size: "M",
      countInStock: 10,
      rating: 4.6,
      numReviews: 15,
      description: "A spring shirt",
    },
    {
      id: 6,
      name: "T-Shirt",
      slug: "t-shirt",
      category: "T-Shirts",
      image: "/images/pants3.jpg",
      price: 45,
      brand: "Levi",
      color: "green",
      size: "M",
      countInStock: 30,
      rating: 5.0,
      numReviews: 25,
      description: "Rock your summer T-shirt",
    },
    {
      id: 7,
      name: "Classic Bag",
      slug: "classic-bag",
      category: "Bag",
      image: "/images/classic-bag.jpeg",
      price: 45,
      brand: "Nike",
      color: "red",
      size: "M",
      countInStock: 0,
      rating: 4.0,
      numReviews: 15,
      description:
        "Our riff on the traditional music case. Originally designed to carry sheet music, this sleek modern version is an exemplary work bag. Slim and light but big enough to carry a slender laptop, your favourite jotter and anything you else you need to create perfect work-life harmony.",
    },
  ],
}
export default data
